### ISSUE TITLE
Store trucks not tied into qb-vehiclekeys

### ISSUE THREAD

**Issue by bruinp8n** [Virus18sp/qb_stores#1]
Allow trucks to work with vehicle keys, same fix as you did in truck_logistics

**Comment by Virus18sp** [comment]
When truck is spawn system give you keys too, check line 488 from client.lua, also in preview see video at 1:38 i receive keys(top notification) also after that i lock and unlock van to show that have keys. Try it.

**Comment by deathjdstn** [comment]
Just issues with it not working with qbus correctly, truck not tied to keys and the menu breaks as well when buying something.

**Comment by Virus18sp** [comment]
> Just issues with it not working with qbus correctly, truck not tied to keys and the menu breaks as well when buying something.

What version of qb are you using? I converted it strictly for https://github.com/qbcore-framework
So, if you have other qbcore version you need to figure out whats wrong on it cause i only work with this one above.

Proof that is working perfectly: https://streamable.com/dtemx9
