### ISSUE TITLE
Failing to buy a store.

### ISSUE THREAD

**Issue by ianvalls90** [Virus18sp/qb_stores#2]
SCRIPT ERROR: @qb_store/server.lua:437: attempt to index a nil value (field 'store_business')
> ref (@qb_stores/server.lua:437

This is happenning after a fresh install of the script, I was just testing it and wanted to buy my first store, but surprise for me, it's not working.....I am getting the "you bought a store" notification tho, but store won't become mine :P.

**Comment by Virus18sp** [comment]
Apart from that error, did you have any sql errors? Did you download the latest version with the commits that were made overnight? I am going to do several more tests but at the moment you are the first person to report this problem, I am using it and I have no problems.

**Comment by ianvalls90** [comment]
I'll re-download and check again, and will let you know in the next few hours.

**Comment by ianvalls90** [comment]
Solved by reinstalling, sorry about that.
